### ISSUE TITLE
Running node-hp-scan-to in kubernetes cluster

### ISSUE THREAD

**Issue by BakermanLP** [manuc66/node-hp-scan-to#632]
**Is your feature request related to a problem? Please describe.**
I wanted to run this in a container in a kubernetes cluster

**Describe the solution you'd like**
Hopefully a working deployment.yaml

**Describe alternatives you've considered**
Running single hosted on my workstation

**Additional context**
I wanted to run this docker container in a kubernetes cluster on some Raspberry Pis. But it seems, that the communication doesn't work quite well between the container and my printer. Possible it is my lack of knowledge of kubernetes. 

I have added the logfile of the container: 
https://pastebin.com/j8xCZM4s

Can somebody lead me in a direction?

Here is also my deployment.yaml
https://pastebin.com/LCLwdBSF

And last, but not least ... is there a nice way to set the hostname tag in this yaml file?

**Comment by manuc66** [comment]
The entry on the printer requested is 'node-hp-scan-to-66fd84b8f6-4bwmc', could you try to make it shorter&simplier, because when trying to register that entry the printer reply with a bad request 400 status code.

**Comment by manuc66** [comment]
I think the issue is not related to that length as mentioned, I made some test on my side and no issues

And it seems you already have some target label registered : node-hp-scan-to-749cfc5475-ngvnq, node-hp-scan-to-749cfc5475-m2tq5, node-hp-scan-to-749cfc5475-85d5m, node-hp-scan-to-749cfc5475-wtb8d, node-hp-scan-to-749cfc5475-5lspq, node-hp-scan-to-749cfc5475-whbds, node-hp-scan-to-749cfc5475-pl7hv, node-hp-scan-to-749cfc5475-xtbfm, node-hp-scan-to-749cfc5475-rgfsq, node-hp-scan-to-749cfc5475-rsk8b, scan2ablage, node-hp-scan-to-ix-chart-64678875b5-p8r7w, node-hp-scan-to-ix-chart-5fb956bc5f-9w8zk, node-hp-scan-to-ix-chart-5fb956bc5f-wt8bp, node-hp-scan-to-ix-chart-5555669db-cj5vk

Maybe there is a hard limit here that prevent you from creating one more. I think powering off the device will remove those excess entries

**Comment by BakermanLP** [comment]
Hello there, I did a factory reset on the printer. After that, all scan-to destinations where deleted. Only powering off doesn't work. BTW ... Factory Reset for this printer HP Envy 7640 is done by pressing four times the back button on the device. 

After that, I started again with the same deployment.yaml and what could I say. It seems to work. 

OK, that's amazing. Thanks for your work!

Oh, and if someone wants to ask, what should that be for. I want to scan some documents and send them automagically to paperless-ngx.

**Comment by BakermanLP** [comment]
And, last but not least to complete this Issue ... here is my lightly changed deployment.yaml file:

`apiVersion: v1
kind: Pod
metadata:
  name: hp-scan-to
  namespace: default
spec:
  containers:
  - image: manuc66/node-hp-scan-to:master
    imagePullPolicy: IfNotPresent
    name: scan-to
    volumeMounts:
      # name must match the volume name below
      - name: nfs
        mountPath: "/scan"
    env:
      - name: IP
        value: "192.168.1.108"
      - name: PUID
        value: "568"
      - name: PGID
        value: "568"
      - name: PATTERN
        value: '"scan"_yyyy-mm-dd_hh:MM:ss'
      - name: TZ
        value: "Europe/Berlin"
  volumes:
  - name: nfs
    nfs:
      server: 192.168.1.20
      path: /mnt/ssd-pool1/nfsk3s
      readOnly: false`

**Comment by manuc66** [comment]
I'm happy that you've found a workaround and that it's working for you

I think in fact you reached what is called the `MaxNetworkDestinations` that is exposed in `WalkupScanToCompCaps` or `WalkupScanDestinations`

Sample payload received from some devices can be found here: https://github.com/manuc66/node-hp-scan-to/blob/master/protocol_doc/HP%20Officejet%206500%20E710n-z.md#get-walkupscantocompwalkupscantocompcaps
