### ISSUE TITLE
HP 9010 - scan using ADF won't start - 409 Conflict

### ISSUE THREAD

**Issue by QuentinC** [manuc66/node-hp-scan-to#750]
**Describe the bug**
Device: HP OfficeJet Pro 9010 series
Command line or Docker : node index.js -d /scan -ip xxxx.xxxxx.xx -p "scan"_dd.mm.yyyy_hh:MM:ss -r 600 -D

Describe what is happening
When scanning using ADF (either single or dual sided), the scan won't start and the printer reports a timeout.

Please attach the output with debug (-D switch, see documentation)
[scan.logs.txt](https://github.com/manuc66/node-hp-scan-to/files/12777187/scan.logs.txt)

**Comment by manuc66** [comment]
Hi @QuentinC 

It looks like your issue is very similar to this one : https://github.com/manuc66/node-hp-scan-to/issues/548

In other word could you make sure that no other sofware instance is monitoring the same entry on the scanner.

I see that 'PaperLess' was the one used, you may add a new flag `-l test409Issue` and select `test409Issue` on the device, I would suggest that you enable the debug logs as well and test again.

Best regards
